cat("Hello from the earth!\n")
cat("We have intelligent people and beautiful cities!\n")
cat("Earth is said to be formed billions years ago, so it has a long history!\n")
cat("People on the earth speak various languages, like English, Chinese, Japanese.\n")
cat("What about you guys?\n")
